apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocksapi
  labels:
    app: stocksapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stocksapi
  template:
    metadata:
      labels:
        app: stocksapi
        
    spec:
      containers:
      - name: stocksapi
        image: docker.io/amrjazouli/stockstransactionswebapi
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5000

        env:
          - name: MONGODB_CONNSTRING
            value: mongodb://mongodb-service:27017

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        emptyDir: {}