apiVersion: v1
kind: Service
metadata:
  name: stocksapi-service
spec:
  #type: LoadBalancer
  type: NodePort
  selector:
    app: stocksapi
  ports:
    - port: 8080
      targetPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017

