services:
  app:
    build: .
    image: amrjazouli/stockstransactionswebapi
    environment: 
      - MONGODB_CONNSTRING=mongodb://db:27017
    ports:
      - "5000:5000"
    depends_on:
      - db

    networks:
      - my-net


  db:
    image: mongo:5.0
    #container_name: db
    restart: unless-stopped

    networks:
      - my-net

  #volumes for app and db:


networks:
  my-net:
    driver: bridge
    