---
- hosts: all
  gather_facts: no
  become: yes


  tasks:


  - name: Copy the flask app file to the Vagrant servers
    copy:  
      src: /$PWD/app.py
      dest: /home/vagrant
      
  
  - name: Copy the requirements.txt file to the Vagrant servers
    copy:
      src: /$PWD/requirements.txt
      dest: /home/vagrant
  
  - name: installing pip3
    apt:
      name: python3-pip
      update_cache: yes

  - name: Installing requirements.txt
    pip:
      requirements: "/vagrant/requirements.txt"

  - name: run flask app
    shell: |
      nohup python3 app.py > logs.txt 2>&1 &


  - name: Install MongoDB
    apt:
      name: mongodb
      state: present

  - name: Start MongoDB service
    service:
      name: mongodb
      state: started
      enabled: yes





  

      
